### ISSUE TITLE
Site displayed not properly in portrait layout on mobile browser.

### ISSUE THREAD

**Issue by yioteh** [fr-end/auto#131]
Site opened on mobile browser (Chrome 45.0.2454.94) on Android 4.4.2 display only header in portrait orientation.
[Portrait](https://lh6.googleusercontent.com/U8faz0xXrRKA22dIdkFxO49VPpsWqPfahwYX-f1vRoNMmyeCFJ3uT1r6085tUOHgUAkKa07YnGA34MRSjkvhhXHE1XQ1JDOJebWNNON_q80HWPgP9q19FJLSGhlCvUZTxe9XZF0iaswLYzYd74djdTeEoHIKvxWCbrERSNECXxStDktcJgicnbePud12CeESVYmIvkHjc6vtaI-gf-zTbPG7ZmpFh8bCu0epUDAcfgDEGNPqjSPkAMVFaphtV9UOrljjnZSE_zds6fdKL7ZDpRAzB-62HDrDEcb2ScIE8hb968mMSt5oJwkeKXNj14ZD8U4_a4c4IzGLGd98VaoWSLKY6LR8V5T80chVAG6reBbPJXnR4y1MAj2TQqND_e7wOYziX4NJcpExIE2t1EZZd6sp77NE8M8IZZiUFOnw2CEOYlM8jX7MrWh6f3ZAFWz4XBy_7DkzaKqHcBaAoNEhs6-dbY_zkrR6PllG0uuobH6zOy_FMoywkhd-5Ffbc1cKee9HIN-BedAX8OukjR917kMHo9aT=s720)
[Landscape](https://lh6.googleusercontent.com/L0pbHPKioFO2dydBQek_izsq6EhGiDEXVFxLhelCAduLIg6ImJ2V2RoYPOcyUbKc2R-_smEWOMPerxH_tsnmLzEruBElAKx2O06iDqUUl09emtJFDSN-RLszNZxJhIhgSib0sSsK06ClcQ0PdTvchT9nxorR8tWzAYi-IBJ7VkTpc-gTIyRZmCbWseKtdhRtvJSCkzdxyowlVJqdtSqJDrR0kKBTPU7DBTNqZWr5wl5-JJABwEljUiTZJBSY2iSR8uIo8LnVP9aXXMLl1HmfLHLR6DM6OcxXAA8ftmtZeyCuYv1BtPE-wv_vr8rHLbW8UiB0LtbHnlwYK1ULHuFayh2iENtzxib5KrW0JcLr4lWtAnXRYNqs5vECLGBVETOWl48ZvDIAE78MpcjSXIAjZqqHPYaCo4cccaI2E5J0W-nkoRNQw3Tx74mn2sXbMT--aSYJecs98TLRR7pIiyAZHE7BFkpYeDPS22JfIYJQHsnFFJc156rioXBMyu9vbTaIfb8t0Jp5BbUjjE_VgrBfNl3rjgUV=s1280)

**Comment by igor0ser** [comment]
fixed
