### ISSUE TITLE
Некорректная подсветка при введении неправильного e-mail в окне регистрации в браузере Mozilla

### ISSUE THREAD

**Issue by ghost** [fr-end/auto#181]
Поле "e-mail" не обведено красным с нижней стороны при введении неправильного e-mail в окне регистрации в браузере Mozilla
Steps:
1. Нажать кнопку "Регистрация";
2. Ввести "abrakadabra" в поле "e-mail";
3. Кликнуть по свободной области окна.

Expected result:
Поле "e-mail" со всех сторон обведено красным
Actual result:
Поле "e-mail" не обведено красным с нижней стороны
![bug005](https://cloud.githubusercontent.com/assets/14974774/10335649/f6e2bedc-6cfa-11e5-9651-cf6bc6ac092e.JPG)

**Comment by igor0ser** [comment]
исправил. убрал подсветку вообще.
